### ISSUE TITLE
How to logically separate ENIs for multiple ASGs

### ISSUE THREAD

**Issue by duxing** [binxio/ec2-network-interface-manager#1]
Great idea to build this tool!

This is more of a question than an issue:
from reading the documentation, I failed to understand how would this work with multiple ASGs  / pools of ENIs.

If you have multiple ASGs, and all instances within each ASG should use a particular pool of ENIs, but not from a different pool. Is there a native configuration / tag that one can use to map an ASG to a pool of ENIs?

Thanks for your time in advance!

**Comment by mvanholsteijn** [comment]
quite easy, you use different names for the `network-interface-manager-pool` tag. For instance:

```
     - Key: network-interface-manager-pool
       Value: fileserver
```

on both the network interfaces and the asg instances.

**Comment by duxing** [comment]
@mvanholsteijn I see. I misunderstood the documentation. thanks for the explanation!
