### ISSUE TITLE
wrong lamba file name

### ISSUE THREAD

**Issue by sjoerdklaveringakpn** [binxio/ec2-network-interface-manager#2]
The v1.4.0 release contains a wrong filename, currently the below seems to be the latest version published to s3:

/cloudformation/network-interface-manager.yaml
  CFNCustomProviderZipFileName:
    Type: String
    Default: lambdas/network-interface-manager-0.1.3.zip

**Comment by mvanholsteijn** [comment]
Hi @sjoerdklaveringakpn thank you for reporting this issue. I have resolved it by publishing release 1.4.0.
